"""The two config files lmk writes (design OOBE §C, the same scheme as kitten's):

  config.yaml          seeded once, ALL COMMENTS, then never touched — it is the user's.
  config.yaml.example  ours: rewritten whenever its content differs, so it is always
                       the current full reference, including the tested-model list.
"""
import os
from pathlib import Path

from lmk.config import (DEFAULT_CACHE_MAX_SIZE, DEFAULT_HOST, DEFAULT_MAX_PARALLEL, DEFAULT_MAX_QUEUE,
                        DEFAULT_MAX_WAIT_SECONDS, DEFAULT_PORT)
from lmk.models import DEFAULT_MODEL_NAME, TESTED_MODELS

_TEMPLATE = f"""\
# lmk configuration. Everything is optional: with nothing uncommented, lmk serves
# {DEFAULT_MODEL_NAME} on http://{DEFAULT_HOST}:{DEFAULT_PORT}. After a change: `lmk up` (it restarts the service).
#
# model:
#   # Name the model in exactly ONE of these three ways:
#   name: {DEFAULT_MODEL_NAME}              # a tested model — the list is in config.yaml.example
#   repo: some-org/Some-Model-MLX-4bit # any MLX model on HuggingFace; untested by us
#   path: /path/to/a/model/dir         # a directory already on this disk; `lmk pull` is not needed
#
#   id: my-model               # what clients send as "model". Default: the name, or the
#                              # repo / directory name in lower case.
#   context_length: 131072     # default: the model's own maximum. If this Mac is short of
#                              # memory lmk lowers it; `lmk status` shows the value in use.
#
# listen:
#   host: {DEFAULT_HOST}
#   port: {DEFAULT_PORT}
#
# cache:                       # lmk keeps the prompts it has already processed on disk, so a
#   dir: ~/.lmk/cache          # conversation continues in about a second — also after a reboot
#   max_size: {DEFAULT_CACHE_MAX_SIZE}             # when full, what was used longest ago is dropped first
#
# requests:
#   max_parallel: {DEFAULT_MAX_PARALLEL}            # answered at the same time. What that gains depends on how long the
#                              # conversations are. Measured on an M3 Ultra with the default model:
#                              #   prompts of a few dozen tokens:  2 at once = 1.7x the speed of one, 4 = 2.2x
#                              #   27k-token conversations:        2 at once = 1.0x (each runs at half speed)
#                              # With 1, a request waits for the one before it and then runs at full speed.
#   max_queue: {DEFAULT_MAX_QUEUE}              # waiting for their turn; one more is refused at once
#   max_wait_seconds: {DEFAULT_MAX_WAIT_SECONDS}      # a request that could not start by then is refused, and told why
#                              # (`lmk status` shows who is waiting, and for what)
#
# log:
#   dir: ~/.lmk/logs
"""

_EXAMPLE_HEADER = """\
# config.yaml.example — the full configuration reference, maintained by lmk and
# refreshed automatically whenever a new version changes it.
# Do not edit this file (it gets overwritten); copy the entries you want into
# config.yaml in this directory.
#
"""


def _model_list() -> str:
    lines = ["#", "# Tested models (model.name). We ran each one with a real agent: tool calls, thinking, images,",
             "# and the on-disk prompt cache all work. `lmk pull` downloads the one you configured into the",
             "# shared HuggingFace cache (~/.cache/huggingface/hub), where other tools can use it too."]
    for name, m in TESTED_MODELS.items():
        lines.append(f"#   {name:<14} {m.size_gb:>5.1f} GB   {m.repo}")
        lines.append(f"#   {'':<14}            {m.note}")
    return "\n".join(lines) + "\n"


def example_text() -> str:
    return _EXAMPLE_HEADER + _TEMPLATE + _model_list()


def _write_atomically(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(path.name + ".tmp")
    tmp.write_text(text)
    os.replace(tmp, path)


def seed_config(path: Path) -> bool:
    """Returns True when the file was created."""
    if path.exists():
        return False
    _write_atomically(path, _TEMPLATE)
    return True


def refresh_example(config_path: Path) -> bool:
    """Compares content, not mtime: a no-op start leaves the file untouched."""
    example = config_path.with_name(config_path.name + ".example")
    want = example_text()
    if example.exists() and example.read_text() == want:
        return False
    _write_atomically(example, want)
    return True
